### ISSUE TITLE
isMinifyEnabled

### ISSUE THREAD

**Issue by Pr4eV** [Breens-Mbaka/BeeTablesCompose#17] opened 2024-06-08 16:04 UTC
hi and thanks for it.
when i use isMinifyEnabled tables not working
please add documants for how use it when isMinifyEnabled is true
thanks..

**Comment by Breens-Mbaka** [comment] 2024-06-08 17:04
Hey @persian1910 we are looking into this issue, we will get back to you as soon as possible.

**Comment by Breens-Mbaka** [comment] 2024-06-09 09:05
Hey @persian1910 so the issue is that when minification is enabled it removes the table data class at build time that's why the table is empty.

To prevent this, annotate your data class with `@Keep` to prevent minification marking the class as unused and removing it.

For example, if you are displaying a list of users in a table and you have a class that holds the name, age and city for example.

`@Keep
data class MyData(
    val name: String,
    val age: Int,
    val city: String
)`

This will fix the issue of the table not appearing if you have minification enabled. Please let me know immediately if this helps.

**Comment by etonotieno** [comment] 2024-06-09 17:10
You could also add a proguard rule to keep the class in your `proguard-rules.pro` file. It's convenient if you have all your models in one package.

`-keep class com.example.modelpackage.*`

**Comment by Breens-Mbaka** [comment] 2024-06-16 04:37
Closing this since option to solve this has been suggested

**Closed as completed by Breens-Mbaka** 2024-06-16 04:37 UTC
